---
title: "edgeR for differential gene expression different model designs
author: "Nisha paudel"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: simplex
    highlight: pygments
    toc: true
    toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Different models
https://f1000research.com/articles/9-1444
Based on quasilikelihood pipeline, NB GLM model with F tests -because of strict error control rate than traditional edgeR and DESeq2

`

## Read data and meta data
```{r}
library(edgeR)
library(limma)
count_data <- read.csv('/Users/nishapaudel/Documents/CASP/Data/Counts.csv', sep =',', header=T, row.names = 1)
sampleinfo <- read.csv("/Users/nishapaudel/Documents/CASP/Data/NEW_design.txt", sep = ',', header = TRUE, row.names = 1, stringsAsFactors = TRUE)
sampleinfo
dim(count_data)
```




```{r}
age <- factor( sampleinfo$Age)
sex <- factor(sampleinfo$Sex)
treatment <- factor(sampleinfo$Treatment)
mm <- model.matrix(~0+sex+treatment) #(no intercept for sex but there is intercept for treatment)
#colnames(design) <- levels(sex)



```

```{r}
y <- DGEList(count_data)
```

## filtering lowly expressed genes

```{r}
keep <- rowSums(cpm(y) > 0.5) >= 2
table(keep)
y <- y[keep, , keep.lib.sizes=FALSE]
```


## Normalization for composition bias
 
```{r}
y <- calcNormFactors(y, method = "TMM")
y$samples
```


```{r}
y <- estimateDisp(y, mm, robust=TRUE)
plotBCV(y)
```


```{r}
fit <- glmQLFit(y, mm, robust=TRUE)
head(fit$coefficients)
```






























```{r}
y <- voom(d, mm, plot = T)
```



```{r}
fit <- lmFit(y, mm)
head(coef(fit))
```










