---
title: "edgeR for differential gene expression - different models"
author: "Nisha paudel"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: simplex
    highlight: pygments
    toc: true
    toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Different models
https://f1000research.com/articles/9-1444
Based on quasilikelihood pipeline, NB GLM model with F tests -because of strict error control rate than traditional edgeR and DESeq2




## Read data and meta data
```{r}
library(edgeR)
library(limma)
count_data <- read.csv('/Users/nishapaudel/Documents/CASP/Data/Counts.csv', sep =',', header=T, row.names = 1)
sampleinfo <- read.csv("/Users/nishapaudel/Documents/CASP/Data/NEW_design.txt", sep = ',', header = TRUE, row.names = 1, stringsAsFactors = TRUE)
sampleinfo
dim(count_data)
```


```{r}
group <- paste(sampleinfo$Age) #
#group <- factor(group)
#table(group)
```


```{r}
y <- DGEList(count_data, group=group)
```

## filtering lowly expressed genes

```{r}
keep <- filterByExpr(y, group = group)
y <- y[keep, , keep.lib.sizes=FALSE]
dim(y)
```


## Normalization for composition bias

```{r}
y <- calcNormFactors(y, method = "TMM")
y$samples
```

## model design without intercept
```{r}
design <- model.matrix(~0+group)
colnames(design)<-levels(group)
```



```{r}
y <- estimateDisp(y, design, robust=TRUE)
plotBCV(y)
```


```{r}
fit <- glmQLFit(y, design, robust=TRUE)
head(fit$coefficients)
```

```{r}
P4 <- makeContrasts( P4-E18  , levels = design)
test <-glmQLFTest(fit, contrast  = P4)
summary(decideTests(test))
```

```{r}
topTags(test)
```







## model design with intercept

```{r}
design <- model.matrix(~group)
colnames(design)<-levels(group)
y <- estimateDisp(y, design, robust=TRUE)
fit <- glmQLFit(y, design, robust=TRUE)
head(fit$coefficients)

```


```{r}
## be careful to relevel in some cases

test <-glmQLFTest(fit, coef=3) #Coefficient:  P4 
summary(decideTests(test))

```


```{r}
topTags(test)
```



## Session information

```{r,session}
sessionInfo()
```


















