---
title: "Normalisation strategies for Differential gene expression"
author: "Nisha paudel"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: simplex
    highlight: pygments
    toc: true
    toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# set echo false if you do not wanna show code
```


From normalization strategy document get the unique elements
No normalisation
Genes   logFC    logCPM         F      PValue
Enpp2         -1.4423936 13.102170  5.756340 0.020251109

TMMwsp
Kcna2         -1.2002866 2.606180 5.391532 0.02433578
Gm12824       -1.0151294 2.736627 5.592410 0.02194897
Efhc2         -1.0828159 2.705967 5.334075 0.02506859

UQ
Wasf3         0.9915001 2.562213 5.343265 0.02497002

RLE
Ptgds   1.1939577 6.917708 5.451831 0.02377350
Pla2g16 1.1360623 5.842765 5.402075 0.02438794

## No Normalization

```{r, warning=FALSE,message=FALSE}
# Load necessary libraries
library(ggplot2)
library(reshape2)
library(tidyverse)
data <- read.csv("./others/no_normalisation_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","F_P4_4","F_P14_1","F_P14_2","F_P14_3","F_P14_4","F_P14_5","F_P14_6","F_P14_7",	"F_P14_8","F_P14_9","F_P14_10","F_P60_S_1","F_P60_S_2","F_P60_S_3","F_P60_S_4","F_P60_S_5","F_P60_S_6","F_P60_S_7","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4","M_P14_1","M_P14_2","M_P14_3","M_P14_4","M_P14_5","M_P14_6","M_P14_7","M_P14_8","M_P14_9","M_P14_10","M_P60_S_1","M_P60_S_2","M_P60_S_3","M_P60_S_4","M_P60_S_5")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh","Cebpb","Nr3c1","Ccr5","Crip2", "Tlr4", "Ttr")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "No normalization") +
  theme_bw() +ggtitle("Impact of No normalization in selected genes ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```

## TMM Normalization

```{r, warning=FALSE,message=FALSE}
data <- read.csv("./others/TMM_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","F_P4_4","F_P14_1","F_P14_2","F_P14_3","F_P14_4","F_P14_5","F_P14_6","F_P14_7",	"F_P14_8","F_P14_9","F_P14_10","F_P60_S_1","F_P60_S_2","F_P60_S_3","F_P60_S_4","F_P60_S_5","F_P60_S_6","F_P60_S_7","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4","M_P14_1","M_P14_2","M_P14_3","M_P14_4","M_P14_5","M_P14_6","M_P14_7","M_P14_8","M_P14_9","M_P14_10","M_P60_S_1","M_P60_S_2","M_P60_S_3","M_P60_S_4","M_P60_S_5")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh","Cebpb","Nr3c1","Ccr5","Crip2", "Tlr4", "Ttr")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "TMM normalization") +
 
  theme_bw() + ggtitle("Impact of No normalization in selected genes ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
  
```


## TMMwsp Normalization

```{r,warning=FALSE,message=FALSE}
data <- read.csv("./others/TMMwsp_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","F_P4_4","F_P14_1","F_P14_2","F_P14_3","F_P14_4","F_P14_5","F_P14_6","F_P14_7",	"F_P14_8","F_P14_9","F_P14_10","F_P60_S_1","F_P60_S_2","F_P60_S_3","F_P60_S_4","F_P60_S_5","F_P60_S_6","F_P60_S_7","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4","M_P14_1","M_P14_2","M_P14_3","M_P14_4","M_P14_5","M_P14_6","M_P14_7","M_P14_8","M_P14_9","M_P14_10","M_P60_S_1","M_P60_S_2","M_P60_S_3","M_P60_S_4","M_P60_S_5")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh","Cebpb","Nr3c1","Ccr5","Crip2", "Tlr4", "Ttr")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "TMMwsp normalization") +
  theme_bw() +ggtitle("Impact of TMMwsp normalization in selected genes ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```


## UQ Normalization

```{r, warning=FALSE, message=FALSE}

data <- read.csv("./others/UQ_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","F_P4_4","F_P14_1","F_P14_2","F_P14_3","F_P14_4","F_P14_5","F_P14_6","F_P14_7",	"F_P14_8","F_P14_9","F_P14_10","F_P60_S_1","F_P60_S_2","F_P60_S_3","F_P60_S_4","F_P60_S_5","F_P60_S_6","F_P60_S_7","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4","M_P14_1","M_P14_2","M_P14_3","M_P14_4","M_P14_5","M_P14_6","M_P14_7","M_P14_8","M_P14_9","M_P14_10","M_P60_S_1","M_P60_S_2","M_P60_S_3","M_P60_S_4","M_P60_S_5")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh","Cebpb","Nr3c1","Ccr5","Crip2", "Tlr4", "Ttr", "Ptgds")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "UQ normalization") +
  theme_bw() +ggtitle("Impact of UQ normalization in selected genes ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))

```

## RLE Normalization

```{r, warning=FALSE, message=FALSE}
data <- read.csv("./others/RLE_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","F_P4_4","F_P14_1","F_P14_2","F_P14_3","F_P14_4","F_P14_5","F_P14_6","F_P14_7",	"F_P14_8","F_P14_9","F_P14_10","F_P60_S_1","F_P60_S_2","F_P60_S_3","F_P60_S_4","F_P60_S_5","F_P60_S_6","F_P60_S_7","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4","M_P14_1","M_P14_2","M_P14_3","M_P14_4","M_P14_5","M_P14_6","M_P14_7","M_P14_8","M_P14_9","M_P14_10","M_P60_S_1","M_P60_S_2","M_P60_S_3","M_P60_S_4","M_P60_S_5")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh","Cebpb","Nr3c1","Ccr5","Crip2", "Tlr4", "Ttr")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "RLE normalization") +
  theme_bw() + ggtitle("Impact of RLE normalization in selected genes ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```


```{r}
data <- read.csv("./others/RLE_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","F_P4_4","F_P14_1","F_P14_2","F_P14_3","F_P14_4","F_P14_5","F_P14_6","F_P14_7",	"F_P14_8","F_P14_9","F_P14_10","F_P60_S_1","F_P60_S_2","F_P60_S_3","F_P60_S_4","F_P60_S_5","F_P60_S_6","F_P60_S_7","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4","M_P14_1","M_P14_2","M_P14_3","M_P14_4","M_P14_5","M_P14_6","M_P14_7","M_P14_8","M_P14_9","M_P14_10","M_P60_S_1","M_P60_S_2","M_P60_S_3","M_P60_S_4","M_P60_S_5")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh","Ttr", "Ptgds","Pla2g16")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "RLE normalization") +
  theme_bw() +ggtitle("Impact of RLE normalization in selected genes ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```

```{r}
data <- read.csv("./others/RLE_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh", "Ptgds","Pla2g16","Efhc2","Enpp2")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "TMM_normalised") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```

```{r}

data <- read.csv("./others/UQ_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh", "Ptgds","Pla2g16","Efhc2","Enpp2","Wasf3", "Kcna2", "Gm12824")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "TMM_normalised") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```

```{r}
data <- read.csv("./others/TMMwsp_counts.csv", sep = ',', header = TRUE, row.names = 1)
# Define the desired column order
desired_columns <- c("F_E18_1","F_E18_2","F_E18_3","F_P4_1","F_P4_2","F_P4_3","M_E18_1","M_E18_2","M_E18_3","M_E18_4","M_P4_1","M_P4_2","M_P4_3","M_P4_4")
# Rearrange the columns based on the desired order
data_rearranged <- data[, desired_columns]
# Replace "gene_names" with the actual row names containing the gene names.
selected_genes <- c("Rpl13","Gapdh", "Ptgds","Pla2g16","Efhc2","Enpp2","Wasf3", "Kcna2", "Gm12824")
selected_counts <- data_rearranged[selected_genes, ]
# Reshape the count matrix into a format suitable for plotting
melted_data <- melt(selected_counts, variable.name = "Sample", value.name = "TMM_normalised")
melted_data$Gene <- rownames(selected_counts)
# Plotting
ggplot(melted_data, aes(x = Sample, y = TMM_normalised, color = Gene, group = Gene)) +
  geom_line() +
  labs(x = "Samples", y = "TMM_normalised") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))
```
## Session info

```{r record_packages}
sessionInfo()
```

