---
title: "smooth_quantile"
author: "Nisha_paudel"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: simplex
    highlight: pygments
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# set echo false if you do not wanna show code
```

## library

<https://bioconductor.org/packages/release/bioc/vignettes/qsmooth/inst/doc/qsmooth.html>

```{r, warning=FALSE, message=FALSE}
library(qsmooth)
library(quantro)
library(minfi)
library(SummarizedExperiment)
library(bodymapRat)
```

## Read

```{r read_csv}
count_data <- read.csv('/Users/nishapaudel/Documents/lps_and_sal_treated/countss', sep =',', header=T)
dim(count_data)
```

```{r}
countMatrix_numeric <- count_data[, -1] # remove first column
head(countMatrix_numeric)
```

```{r}
row_sums <- rowSums(countMatrix_numeric)
countMatrix_numeric <- countMatrix_numeric[row_sums >= 10, ]

dim(countMatrix_numeric)
```

```{r}
design <- read.csv('/Users/nishapaudel/Documents/lps_and_sal_treated/design.txt', sep =',', header=T)
design$Treatment
```

## Raw data viz

```{r}
matboxplot(log2(countMatrix_numeric+1), groupFactor = factor(design$Treatment),
           main = "Raw data", xaxt="n", 
           ylab = "Expression (log2 scale)")
axis(1, at=seq_len(length(as.character(design$Treatment))),
     labels=FALSE)
text(seq_len(length(design$Treatment)), par("usr")[3] -2, 
     labels = design$Treatment, srt = 90, pos = 1, xpd = TRUE)


```

```{r}
qs_norm_e1 <- qsmooth(object = countMatrix_numeric, group_factor = design$Treatment)
qs_norm_e1  
#new <- qs_norm_e1+1
#head(new)
```

## smooth quantile viz

```{r}
matboxplot(log2(qsmoothData(qs_norm_e1)+1), 
           groupFactor = design$Treatment, xaxt="n",
           main = "qsmooth normalized data", 
           ylab = "Expression (log2 scale)")
axis(1, at=seq_len(length(design$Treatment)), labels=FALSE)
text(seq_len(length(design$Treatment)), par("usr")[3] -2, 
     labels = design$Treatment, srt = 90, pos = 1, xpd = TRUE)
```

```{r}
matdensity(log2(qsmoothData(qs_norm_e1)+1), groupFactor = design$Treatment,
           main = "qsmooth normalized data",
           xlab = "Expression (log2 scale)", ylab = "density")
legend('topright', levels(factor(design$Treatment)), col = 1:2, lty = 1)
```

## my own figure

```{r}
# Load the required library
library(qsmooth)

# Sample count matrix (replace this with your actual count matrix)
# The rows represent genes, and the columns represent cells/samples
count_matrix <- matrix(c(10, 5, 2, 0, 8, 1, 12, 6, 3, 7, 4, 1), nrow = 4, byrow = TRUE)

# The row names should be gene IDs or gene names
rownames(count_matrix) <- c("GeneA", "GeneB", "GeneC", "GeneD")

# The column names should be cell/sample IDs
colnames(count_matrix) <- c("Cell1", "Cell2", "Cell3")

# Perform quantile smoothing using the qsmooth function
smoothed_count_matrix <- qsmooth(count_matrix)

# Print the smoothed count matrix
print(smoothed_count_matrix)

```



```{r}
#boxplot(log2(qsmoothData(qs_norm_e1)+1, ylab="smooth quantile",las=2, col = "lightblue4",main="smooth quantile normalisation")
## Let's add a blue horizontal line that corresponds to the median logCPM
#abline(h=3.7,col="blue")
#abline(h = 1.50, col = "black", lwd = 1)
```

## save

```{r save_file}
#write.csv(count_data_with_lengths, file ="new_countdata_with_length.csv" , quote = FALSE, row.names = T)
```

## Session info

```{r record_packages}
sessionInfo()
```
