---
title: "Comparing the unique elements from the venn diagram"
author: "Nisha paudel"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: simplex
    highlight: pygments
    toc: true
    toc_float: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# set echo false if you do not wanna show code
```




```{r}
data <- read.csv("./others/no_normalisation_unique_elements", sep = ',', header = TRUE, row.names = 1)
data_pvalues <- read.csv("./others/no_normalisation.csv", sep = ',', header = TRUE, row.names = 1)
selected_genes <- data$x
selected_counts <- data_pvalues[selected_genes, ]
selected_counts

```


```{r}

data <- read.csv("./others/TMMwsp_unique_elements", sep = ',', header = TRUE, row.names = 1)
data_pvalues <- read.csv("./others/TMMwsp.csv", sep = ',', header = TRUE, row.names = 1)
selected_genes <- data$x
selected_counts <- data_pvalues[selected_genes, ]
selected_counts


```

```{r}
data <- read.csv("./others/UQ_unique_elements", sep = ',', header = TRUE, row.names = 1)
data_pvalues <- read.csv("./others/UQ.csv", sep = ',', header = TRUE, row.names = 1)
selected_genes <- data$x
selected_counts <- data_pvalues[selected_genes, ]
selected_counts
```

```{r}
data <- read.csv("./others/RLE_unique_elements.csv", sep = ',', header = TRUE, row.names = 1)
data_pvalues <- read.csv("./others/RLE.csv", sep = ',', header = TRUE, row.names = 1)
selected_genes <- data$x
selected_counts <- data_pvalues[selected_genes, ]
selected_counts
```

